import { useEffect, useState } from 'react'
import axios from 'axios'
import { BriefcaseBusiness, Check, CircleAlert, ClipboardList, LogOut, Pencil, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react'
import './App.css'

const api = axios.create({ baseURL: `${window.location.protocol}//${window.location.hostname}:8080/api` })
api.interceptors.request.use((config) => { const token = localStorage.getItem('trackerToken'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })
const statuses = ['APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED']
const colors = { APPLIED: 'blue', INTERVIEW: 'amber', OFFER: 'green', REJECTED: 'red' }
const decode = (token) => { try { return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))) } catch { return null } }

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('trackerToken')); const [authMode, setAuthMode] = useState('login'); const [toast, setToast] = useState(null)
  const role = decode(token || '')?.role || 'USER'; const [view, setView] = useState(role === 'ADMIN' ? 'admin' : 'dashboard')
  useEffect(() => { const destination = role === 'ADMIN' ? '/admin' : '/dashboard'; if (window.location.pathname !== destination) window.history.replaceState({}, '', destination) }, [role])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(null), 3500); return () => clearTimeout(timer) } }, [toast])
  const notify = (message, type = 'success') => setToast({ message, type })
  const navigate = (nextView) => { window.history.pushState({}, '', `/${nextView}`); setView(nextView) }
  const login = (next) => { localStorage.setItem('trackerToken', next); setToken(next); navigate(decode(next)?.role === 'ADMIN' ? 'admin' : 'dashboard') }
  const logout = () => { localStorage.removeItem('trackerToken'); setToken(null) }
  if (!token) return <Auth mode={authMode} setMode={setAuthMode} onLogin={login} notify={notify} toast={toast} />
  return <><header className="topbar"><div className="nav"><b className="brand"><BriefcaseBusiness size={19} /> Trackr</b><div className="nav-actions"><span className="role"><i /> {role === 'ADMIN' ? 'Administrator' : 'Workspace'}</span>{role === 'ADMIN' && <button className={view === 'admin' ? 'nav-active' : ''} onClick={() => navigate('admin')}><ShieldCheck size={16} /> Admin</button>}<button className="logout" title="Log out" onClick={logout}><LogOut size={16} /></button></div></div></header><main className="shell">{view === 'admin' && role === 'ADMIN' ? <Admin notify={notify} /> : <Dashboard notify={notify} />}</main>{toast && <Toast data={toast} />}</>
}

function Auth({ mode, setMode, onLogin, notify, toast }) { const [form, setForm] = useState({ username: '', email: '', password: '' }); const [busy, setBusy] = useState(false); const set = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); setBusy(true); try { const { data } = await api.post(`/auth/${mode}`, mode === 'login' ? { username: form.username, password: form.password } : form); onLogin(data.token) } catch (error) { notify(error.response?.data || 'Request failed', 'error') } finally { setBusy(false) } }; return <div className="auth"><aside><BriefcaseBusiness size={24} /><small>CAREER OPERATIONS</small><h1>Make every application count.</h1><p>One calm workspace for the roles you are chasing and the next move ahead.</p></aside><section className="auth-form"><b className="brand"><BriefcaseBusiness size={19} /> Trackr</b><h2>{mode === 'login' ? 'Welcome back' : 'Start tracking'}</h2><p>Sign in to your application workspace.</p><form onSubmit={submit}><Field label="Username" value={form.username} set={set('username')} placeholder="you" />{mode === 'register' && <Field label="Email" type="email" value={form.email} set={set('email')} placeholder="you@company.com" />}<Field label="Password" type="password" value={form.password} set={set('password')} placeholder="••••••••" /><button className="primary wide" disabled={busy}>{busy ? 'Working...' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="switch" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</button></section>{toast && <Toast data={toast} />}</div> }
function Field({ label, type = 'text', value, set, placeholder }) { return <label className="field"><span>{label}</span><input required type={type} value={value} onChange={set} placeholder={placeholder} /></label> }
function Toast({ data }) { return <div className={`toast ${data.type}`}><span>{data.type === 'error' ? <CircleAlert size={17} /> : <Check size={17} />}</span>{data.message}</div> }
function Heading({ eyebrow, title, action }) { return <div className="heading"><div><small>{eyebrow}</small><h1>{title}</h1></div>{action}</div> }
function Stat({ label, value, tone = '' }) { return <div className="stat"><span className={tone}>{tone ? '●' : <ClipboardList size={18} />}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function Badge({ status }) { return <b className={`badge ${colors[status]}`}>{status[0] + status.slice(1).toLowerCase()}</b> }

function Dashboard({ notify }) { const [apps, setApps] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const load = async () => { try { setApps((await api.get('/applications')).data) } catch { notify('Could not load applications', 'error') } finally { setLoading(false) } }; useEffect(() => { load() }, []); const filtered = apps.filter((a) => (filter === 'ALL' || a.status === filter) && a.companyName.toLowerCase().includes(query.toLowerCase())); const counts = Object.fromEntries(statuses.map((s) => [s, apps.filter((a) => a.status === s).length])); const save = async (form) => { try { const res = editing?.id ? await api.put(`/applications/${editing.id}`, form) : await api.post('/applications', form); setApps(editing?.id ? apps.map((a) => a.id === editing.id ? res.data : a) : [...apps, res.data]); setEditing(null); notify(editing?.id ? 'Application updated' : 'Application added') } catch (error) { notify(error.response?.data || 'Could not save application', 'error') } }; const remove = async (id) => { if (!window.confirm('Delete this application?')) return; try { await api.delete(`/applications/${id}`); setApps(apps.filter((a) => a.id !== id)); notify('Application deleted') } catch { notify('Could not delete application', 'error') } }; return <><Heading eyebrow="MY SEARCH" title="Application workspace" action={<button className="primary" onClick={() => setEditing({})}><Plus size={17} /> Add application</button>} /><div className="stats">{[['Total applications', apps.length, ''], ['Applied', counts.APPLIED, 'blue'], ['Interview', counts.INTERVIEW, 'amber'], ['Offer', counts.OFFER, 'green'], ['Rejected', counts.REJECTED, 'red']].map(([label, value, tone]) => <Stat key={label} label={label} value={value} tone={tone} />)}</div><section className="panel"><div className="panel-head"><div><h3>All applications</h3><p>Keep the next step visible.</p></div><div className="filters"><label className="search"><Search size={16} /><input placeholder="Search company" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="ALL">All statuses</option>{statuses.map((s) => <option key={s}>{s}</option>)}</select></div></div><ApplicationTable apps={filtered} loading={loading} onEdit={setEditing} onDelete={remove} /></section>{editing && <Modal initial={editing} onClose={() => setEditing(null)} onSave={save} />}</> }

function Admin({ notify }) { const [data, setData] = useState({ users: [], apps: [], stats: {} }); const [query, setQuery] = useState(''); useEffect(() => { Promise.all([api.get('/admin/users'), api.get('/admin/applications'), api.get('/admin/stats')]).then(([u, a, s]) => setData({ users: u.data, apps: a.data, stats: s.data })).catch(() => notify('Could not load admin data', 'error')) }, []); const users = data.users.filter((u) => `${u.username} ${u.email}`.toLowerCase().includes(query.toLowerCase())); const apps = data.apps.filter((a) => `${a.companyName} ${a.jobRole} ${a.user?.username}`.toLowerCase().includes(query.toLowerCase())); return <><Heading eyebrow="ADMIN CONSOLE" title="Search overview" action={<span className="admin-pill"><ShieldCheck size={15} /> Live data</span>} /><div className="stats">{[['Total users', data.stats.totalUsers || 0, ''], ['Applications', data.stats.totalApplications || 0, ''], ...statuses.map((s) => [s, data.stats.byStatus?.[s] || 0, colors[s]])].map(([label, value, tone]) => <Stat key={label} label={label} value={value} tone={tone} />)}</div><div className="admin-tools"><h3>People & activity</h3><label className="search"><Search size={16} /><input placeholder="Search users or applications" value={query} onChange={(e) => setQuery(e.target.value)} /></label></div><section className="panel"><div className="panel-head"><div><h3>Users</h3><p>Every account in the workspace.</p></div></div><table><thead><tr><th>ID</th><th>Username</th><th>Email</th><th>Role</th><th>Joined</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.id}</td><td className="strong">{u.username}</td><td>{u.email}</td><td><b className="admin-pill">{u.role}</b></td><td>{u.createdAt ? new Date(u.createdAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></section><section className="panel"><div className="panel-head"><div><h3>All applications</h3><p>A complete view across applicants.</p></div></div><ApplicationTable apps={apps} admin /></section></> }
function ApplicationTable({ apps, loading, onEdit, onDelete, admin }) { return <div className="table-wrap"><table><thead><tr><th>Company</th><th>Role</th>{admin && <th>Applicant</th>}<th>Status</th><th>Date applied</th>{!admin && <th />}</tr></thead><tbody>{loading ? <tr><td colSpan="6" className="empty">Loading applications...</td></tr> : apps.length === 0 ? <tr><td colSpan="6" className="empty">No applications match your filters.</td></tr> : apps.map((a) => <tr key={a.id}><td className="strong">{a.companyName}</td><td>{a.jobRole}</td>{admin && <td>{a.user?.username || 'Unknown'}</td>}<td><Badge status={a.status} /></td><td>{a.dateApplied || '—'}</td>{!admin && <td className="actions"><button title="Edit" onClick={() => onEdit(a)}><Pencil size={15} /></button><button title="Delete" onClick={() => onDelete(a.id)}><Trash2 size={15} /></button></td>}</tr>)}</tbody></table></div> }
function Modal({ initial, onClose, onSave }) { const [form, setForm] = useState({ companyName: initial.companyName || '', jobRole: initial.jobRole || '', status: initial.status || 'APPLIED', dateApplied: initial.dateApplied || new Date().toISOString().slice(0, 10), notes: initial.notes || '' }); const set = (key) => (e) => setForm({ ...form, [key]: e.target.value }); return <div className="backdrop"><div className="modal"><div className="modal-head"><div><small>{initial.id ? 'EDIT RECORD' : 'NEW RECORD'}</small><h2>{initial.id ? 'Update application' : 'Add application'}</h2></div><button className="icon" onClick={onClose}><X size={18} /></button></div><form onSubmit={(e) => { e.preventDefault(); onSave(form) }}><div className="grid"><Field label="Company" value={form.companyName} set={set('companyName')} placeholder="Acme Inc." /><Field label="Role" value={form.jobRole} set={set('jobRole')} placeholder="Product Designer" /><label className="field"><span>Status</span><select value={form.status} onChange={set('status')}>{statuses.map((s) => <option key={s}>{s}</option>)}</select></label><Field label="Date applied" type="date" value={form.dateApplied} set={set('dateApplied')} /></div><label className="field"><span>Notes <small>Optional</small></span><textarea value={form.notes} onChange={set('notes')} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Check size={16} /> Save application</button></div></form></div></div> }
