import { useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { ArrowDownUp, BriefcaseBusiness, Check, CircleAlert, ClipboardList, ExternalLink, LayoutDashboard, ListChecks, LogOut, MapPin, Pencil, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react'
import './App.css'

const api = axios.create({ baseURL: `${window.location.protocol}//${window.location.hostname}:8080/api` })
api.interceptors.request.use((config) => { const token = localStorage.getItem('trackerToken'); if (token) config.headers.Authorization = `Bearer ${token}`; return config })
const statuses = ['SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED']
const colors = { SAVED: 'violet', APPLIED: 'blue', INTERVIEW: 'amber', OFFER: 'green', REJECTED: 'red' }
const hexColors = { SAVED: '#7c5cff', APPLIED: '#1769e0', INTERVIEW: '#c98716', OFFER: '#208d5e', REJECTED: '#d25054' }
const decode = (token) => { try { return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))) } catch { return null } }
const errorMessage = (error, fallback) => { const data = error.response?.data; if (typeof data === 'string') return data; if (data?.message) return data.message; return fallback }

export default function App() {
  const [token, setToken] = useState(localStorage.getItem('trackerToken')); const [authMode, setAuthMode] = useState('login'); const [toast, setToast] = useState(null)
  const role = decode(token || '')?.role || 'USER'; const isAdmin = role === 'ADMIN'; const [view, setView] = useState(isAdmin ? 'admin' : 'dashboard')
  useEffect(() => { const destination = isAdmin ? '/admin' : '/dashboard'; if (window.location.pathname !== destination) window.history.replaceState({}, '', destination) }, [isAdmin])
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(null), 3500); return () => clearTimeout(timer) } }, [toast])
  const notify = (message, type = 'success') => setToast({ message, type })
  const navigate = (nextView) => { window.history.pushState({}, '', `/${nextView}`); setView(nextView) }
  const login = (next) => { localStorage.setItem('trackerToken', next); setToken(next); navigate(decode(next)?.role === 'ADMIN' ? 'admin' : 'dashboard') }
  const logout = () => { localStorage.removeItem('trackerToken'); setToken(null) }
  const appsState = useApplications(notify, !isAdmin && !!token)
  if (!token) return <Auth mode={authMode} setMode={setAuthMode} onLogin={login} notify={notify} toast={toast} />
  return <><header className="topbar"><div className="nav"><b className="brand"><BriefcaseBusiness size={19} /> Trackr</b><div className="nav-actions"><span className="role"><i /> {isAdmin ? 'Administrator' : 'Workspace'}</span>{!isAdmin && <button className={view === 'dashboard' ? 'nav-active' : ''} onClick={() => navigate('dashboard')}><LayoutDashboard size={16} /> Dashboard</button>}{!isAdmin && <button className={view === 'applications' ? 'nav-active' : ''} onClick={() => navigate('applications')}><ListChecks size={16} /> Applications</button>}{isAdmin && <button className={view === 'admin' ? 'nav-active' : ''} onClick={() => navigate('admin')}><ShieldCheck size={16} /> Admin</button>}<button className="logout" title="Log out" onClick={logout}><LogOut size={16} /></button></div></div></header><main className="shell">{isAdmin ? <Admin notify={notify} /> : view === 'applications' ? <Applications notify={notify} appsState={appsState} /> : <Overview appsState={appsState} onNavigate={navigate} />}</main>{toast && <Toast data={toast} />}</>
}

function useApplications(notify, enabled) {
  const [apps, setApps] = useState([]); const [loading, setLoading] = useState(enabled); const [loadError, setLoadError] = useState(false); const [savingStatusId, setSavingStatusId] = useState(null)
  const load = async () => { setLoading(true); setLoadError(false); try { setApps((await api.get('/applications')).data) } catch { setLoadError(true); notify('Could not load applications', 'error') } finally { setLoading(false) } }
  useEffect(() => { if (enabled) load() }, [enabled])
  const save = async (form, editing) => { try { const res = editing?.id ? await api.put(`/applications/${editing.id}`, form) : await api.post('/applications', form); setApps((prev) => editing?.id ? prev.map((a) => a.id === editing.id ? res.data : a) : [...prev, res.data]); notify(editing?.id ? 'Application updated' : 'Application added'); return true } catch (error) { notify(errorMessage(error, 'Could not save application'), 'error'); return false } }
  const remove = async (id) => { try { await api.delete(`/applications/${id}`); setApps((prev) => prev.filter((a) => a.id !== id)); notify('Application deleted') } catch { notify('Could not delete application', 'error') } }
  const changeStatus = async (id, status) => { setSavingStatusId(id); try { const res = await api.patch(`/applications/${id}/status`, { status }); setApps((prev) => prev.map((a) => a.id === id ? res.data : a)); notify('Status updated') } catch (error) { notify(errorMessage(error, 'Could not update status'), 'error') } finally { setSavingStatusId(null) } }
  return { apps, loading, loadError, savingStatusId, load, save, remove, changeStatus }
}

function Auth({ mode, setMode, onLogin, notify, toast }) { const [form, setForm] = useState({ username: '', email: '', password: '' }); const [busy, setBusy] = useState(false); const set = (key) => (event) => setForm({ ...form, [key]: event.target.value }); const submit = async (event) => { event.preventDefault(); setBusy(true); try { const { data } = await api.post(`/auth/${mode}`, mode === 'login' ? { username: form.username, password: form.password } : form); onLogin(data.token) } catch (error) { notify(errorMessage(error, 'Request failed'), 'error') } finally { setBusy(false) } }; return <div className="auth"><aside><BriefcaseBusiness size={24} /><small>CAREER OPERATIONS</small><h1>Make every application count.</h1><p>One calm workspace for the roles you are chasing and the next move ahead.</p></aside><section className="auth-form"><b className="brand"><BriefcaseBusiness size={19} /> Trackr</b><h2>{mode === 'login' ? 'Welcome back' : 'Start tracking'}</h2><p>Sign in to your application workspace.</p><form onSubmit={submit}><Field label="Username" value={form.username} set={set('username')} placeholder="you" minLength={3} />{mode === 'register' && <Field label="Email" type="email" value={form.email} set={set('email')} placeholder="you@company.com" />}<Field label="Password" type="password" value={form.password} set={set('password')} placeholder="••••••••" minLength={mode === 'register' ? 8 : undefined} /><button className="primary wide" disabled={busy}>{busy ? 'Working...' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="switch" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Sign in'}</button></section>{toast && <Toast data={toast} />}</div> }
function Field({ label, type = 'text', value, set, placeholder, minLength, required = true }) { return <label className="field"><span>{label}{!required && <small> Optional</small>}</span><input required={required} type={type} value={value} onChange={set} placeholder={placeholder} minLength={minLength} /></label> }
function Toast({ data }) { return <div className={`toast ${data.type}`}><span>{data.type === 'error' ? <CircleAlert size={17} /> : <Check size={17} />}</span>{data.message}</div> }
function Heading({ eyebrow, title, action }) { return <div className="heading"><div><small>{eyebrow}</small><h1>{title}</h1></div>{action}</div> }
function Stat({ label, value, tone = '' }) { return <div className="stat"><span className={tone}>{tone ? '●' : <ClipboardList size={18} />}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function Badge({ status }) { return <b className={`badge ${colors[status]}`}>{status[0] + status.slice(1).toLowerCase()}</b> }

function Overview({ appsState, onNavigate }) { const { apps, loading, loadError, load, save, remove } = appsState; const [editing, setEditing] = useState(null); const counts = Object.fromEntries(statuses.map((s) => [s, apps.filter((a) => a.status === s).length])); const total = apps.length; const recent = useMemo(() => [...apps].sort((a, b) => (b.dateApplied || '').localeCompare(a.dateApplied || '')).slice(0, 5), [apps]); const removeApp = async (id) => { if (!window.confirm('Delete this application?')) return; await remove(id) }; return <><Heading eyebrow="OVERVIEW" title="Your job search at a glance" action={<div className="quick-actions"><button className="primary" onClick={() => setEditing({})}><Plus size={17} /> Add application</button><button className="secondary" onClick={() => onNavigate('applications')}><ListChecks size={16} /> View all applications</button></div>} /><div className="stats">{[['Total applications', total, ''], ['Saved', counts.SAVED, 'violet'], ['Applied', counts.APPLIED, 'blue'], ['Interview', counts.INTERVIEW, 'amber'], ['Offer', counts.OFFER, 'green'], ['Rejected', counts.REJECTED, 'red']].map(([label, value, tone]) => <Stat key={label} label={label} value={value} tone={tone} />)}</div>{loading ? <div className="state-block"><p>Loading your dashboard...</p></div> : loadError ? <ErrorState onRetry={load} /> : total === 0 ? <EmptyState onAdd={() => setEditing({})} /> : <div className="dash-grid"><section className="panel chart-panel"><div className="panel-head"><div><h3>Status distribution</h3><p>Where your applications currently stand.</p></div></div><StatusChart counts={counts} total={total} /></section><section className="panel"><div className="panel-head"><div><h3>Recent applications</h3><p>Your latest updates.</p></div><button className="secondary" onClick={() => onNavigate('applications')}>View all</button></div><div className="table-wrap"><table><thead><tr><th>Company</th><th>Role</th><th>Status</th><th>Date applied</th><th /></tr></thead><tbody>{recent.map((a) => <tr key={a.id}><td className="strong">{a.companyName}</td><td>{a.jobRole}</td><td><Badge status={a.status} /></td><td>{a.dateApplied || '—'}</td><td className="actions"><button title="Edit" onClick={() => setEditing(a)}><Pencil size={15} /></button><button title="Delete" onClick={() => removeApp(a.id)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div></section></div>}{editing && <Modal initial={editing} onClose={() => setEditing(null)} onSave={async (form) => { const ok = await save(form, editing); if (ok) setEditing(null) }} />}</> }

function StatusChart({ counts, total }) { let cumulative = 0; const segments = statuses.map((s) => { const value = counts[s] || 0; const pct = total ? (value / total) * 100 : 0; const start = cumulative; cumulative += pct; return { s, start, end: cumulative } }); const gradient = total ? segments.map(({ s, start, end }) => `${hexColors[s]} ${start}% ${end}%`).join(', ') : '#e8edf2 0% 100%'; return <div className="chart"><div className="donut" style={{ background: `conic-gradient(${gradient})` }}><span>{total}<small>Total</small></span></div><ul className="legend">{statuses.map((s) => <li key={s}><i className={colors[s]} /> {s[0] + s.slice(1).toLowerCase()} <b>{counts[s] || 0}</b></li>)}</ul></div> }

function EmptyState({ onAdd }) { return <div className="state-block"><ClipboardList size={22} /><p>No applications yet. Start tracking your job search.</p><button className="primary" onClick={onAdd}><Plus size={16} /> Add your first application</button></div> }

function Applications({ appsState }) { const { apps, loading, loadError, load, save, remove, changeStatus, savingStatusId } = appsState; const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [sortDir, setSortDir] = useState('desc'); const [editing, setEditing] = useState(null); const filtered = apps.filter((a) => (filter === 'ALL' || a.status === filter) && `${a.companyName} ${a.jobRole}`.toLowerCase().includes(query.toLowerCase())); const sorted = useMemo(() => [...filtered].sort((a, b) => { const diff = (a.dateApplied || '').localeCompare(b.dateApplied || ''); return sortDir === 'asc' ? diff : -diff }), [filtered, sortDir]); const removeApp = async (id) => { if (!window.confirm('Delete this application?')) return; await remove(id) }; return <><Heading eyebrow="MY SEARCH" title="Application workspace" action={<button className="primary" onClick={() => setEditing({})}><Plus size={17} /> Add application</button>} /><section className="panel"><div className="panel-head"><div><h3>All applications</h3><p>Keep the next step visible.</p></div><div className="filters"><label className="search"><Search size={16} /><input placeholder="Search company or role" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="ALL">All statuses</option>{statuses.map((s) => <option key={s}>{s}</option>)}</select><button type="button" className="secondary sort-toggle" onClick={() => setSortDir(sortDir === 'asc' ? 'desc' : 'asc')} title="Toggle sort order"><ArrowDownUp size={15} /> Date {sortDir === 'asc' ? '↑' : '↓'}</button></div></div>{loadError && !loading ? <ErrorState onRetry={load} /> : <ApplicationTable apps={sorted} loading={loading} onEdit={setEditing} onDelete={removeApp} onStatusChange={changeStatus} savingStatusId={savingStatusId} />}</section>{editing && <Modal initial={editing} onClose={() => setEditing(null)} onSave={async (form) => { const ok = await save(form, editing); if (ok) setEditing(null) }} />}</> }

function ErrorState({ onRetry }) { return <div className="state-block error"><CircleAlert size={22} /><p>Something went wrong while loading your applications.</p><button className="secondary" onClick={onRetry}>Try again</button></div> }

function Admin({ notify }) { const [data, setData] = useState({ users: [], apps: [], stats: {} }); const [query, setQuery] = useState(''); useEffect(() => { Promise.all([api.get('/admin/users'), api.get('/admin/applications'), api.get('/admin/stats')]).then(([u, a, s]) => setData({ users: u.data, apps: a.data, stats: s.data })).catch(() => notify('Could not load admin data', 'error')) }, []); const users = data.users.filter((u) => `${u.username} ${u.email}`.toLowerCase().includes(query.toLowerCase())); const apps = data.apps.filter((a) => `${a.companyName} ${a.jobRole} ${a.user?.username}`.toLowerCase().includes(query.toLowerCase())); return <><Heading eyebrow="ADMIN CONSOLE" title="Search overview" action={<span className="admin-pill"><ShieldCheck size={15} /> Live data</span>} /><div className="stats">{[['Total users', data.stats.totalUsers || 0, ''], ['Applications', data.stats.totalApplications || 0, ''], ...statuses.map((s) => [s, data.stats.byStatus?.[s] || 0, colors[s]])].map(([label, value, tone]) => <Stat key={label} label={label} value={value} tone={tone} />)}</div><div className="admin-tools"><h3>People & activity</h3><label className="search"><Search size={16} /><input placeholder="Search users or applications" value={query} onChange={(e) => setQuery(e.target.value)} /></label></div><section className="panel"><div className="panel-head"><div><h3>Users</h3><p>Every account in the workspace.</p></div></div><table><thead><tr><th>ID</th><th>Username</th><th>Email</th><th>Role</th><th>Joined</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.id}</td><td className="strong">{u.username}</td><td>{u.email}</td><td><b className="admin-pill">{u.role}</b></td><td>{u.createdAt ? new Date(u.createdAt).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></section><section className="panel"><div className="panel-head"><div><h3>All applications</h3><p>A complete view across applicants.</p></div></div><ApplicationTable apps={apps} admin /></section></> }
function ApplicationTable({ apps, loading, onEdit, onDelete, onStatusChange, savingStatusId, admin }) { const columnCount = 6; return <div className="table-wrap"><table><thead><tr><th>Company</th><th>Role</th><th>Location</th>{admin && <th>Applicant</th>}<th>Status</th><th>Date applied</th>{!admin && <th />}</tr></thead><tbody>{loading ? <tr><td colSpan={columnCount} className="empty">Loading applications...</td></tr> : apps.length === 0 ? <tr><td colSpan={columnCount} className="empty">No applications match your filters.</td></tr> : apps.map((a) => <tr key={a.id}><td className="strong">{a.companyName}{a.jobUrl && <a className="job-link" href={a.jobUrl} target="_blank" rel="noreferrer" title="Open job posting"><ExternalLink size={13} /></a>}</td><td>{a.jobRole}</td><td>{a.location ? <span className="location"><MapPin size={13} /> {a.location}</span> : '—'}</td>{admin && <td>{a.user?.username || 'Unknown'}</td>}<td>{admin ? <Badge status={a.status} /> : <select className="status-select" value={a.status} disabled={savingStatusId === a.id} onChange={(e) => onStatusChange(a.id, e.target.value)}>{statuses.map((s) => <option key={s} value={s}>{s[0] + s.slice(1).toLowerCase()}</option>)}</select>}</td><td>{a.dateApplied || '—'}</td>{!admin && <td className="actions"><button title="Edit" onClick={() => onEdit(a)}><Pencil size={15} /></button><button title="Delete" onClick={() => onDelete(a.id)}><Trash2 size={15} /></button></td>}</tr>)}</tbody></table></div> }
function Modal({ initial, onClose, onSave }) { const [form, setForm] = useState({ companyName: initial.companyName || '', jobRole: initial.jobRole || '', location: initial.location || '', jobUrl: initial.jobUrl || '', status: initial.status || 'APPLIED', dateApplied: initial.dateApplied || new Date().toISOString().slice(0, 10), notes: initial.notes || '' }); const [busy, setBusy] = useState(false); const set = (key) => (e) => setForm({ ...form, [key]: e.target.value }); const submit = async (e) => { e.preventDefault(); setBusy(true); try { await onSave(form) } finally { setBusy(false) } }; return <div className="backdrop"><div className="modal"><div className="modal-head"><div><small>{initial.id ? 'EDIT RECORD' : 'NEW RECORD'}</small><h2>{initial.id ? 'Update application' : 'Add application'}</h2></div><button className="icon" onClick={onClose}><X size={18} /></button></div><form onSubmit={submit}><div className="grid"><Field label="Company" value={form.companyName} set={set('companyName')} placeholder="Acme Inc." /><Field label="Role" value={form.jobRole} set={set('jobRole')} placeholder="Product Designer" /><Field label="Location" value={form.location} set={set('location')} placeholder="Remote, London..." required={false} /><Field label="Job URL" type="url" value={form.jobUrl} set={set('jobUrl')} placeholder="https://company.com/careers/123" required={false} /><label className="field"><span>Status</span><select value={form.status} onChange={set('status')}>{statuses.map((s) => <option key={s}>{s}</option>)}</select></label><Field label="Date applied" type="date" value={form.dateApplied} set={set('dateApplied')} /></div><label className="field"><span>Notes <small>Optional</small></span><textarea value={form.notes} onChange={set('notes')} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}><Check size={16} /> {busy ? 'Saving...' : 'Save application'}</button></div></form></div></div> }
